//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 4.0.2
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace Unity.Services.Vivox {

internal enum vx_connection_state {
  connection_state_disconnected = 0,
  connection_state_connected = 1,
  connection_state_recovering = 3,
  connection_state_failed_to_recover = 4,
  connection_state_recovered = 5
}

}
