//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 4.0.2
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace Unity.Services.Vivox {

internal enum vx_channel_rolloff_curve_type {
  channel_rolloff_curve_type_none = 0,
  channel_rolloff_curve_type_inverse_distance_clamped = 1,
  channel_rolloff_curve_type_linear_distance_clamped = 2,
  channel_rolloff_curve_type_exponential_distance_clamped = 3
}

}
