//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 4.0.2
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace Unity.Services.Vivox {

internal enum vx_noise_suppression_level {
  noise_suppression_low = 0,
  noise_suppression_moderate = 1,
  noise_suppression_high = 2,
  noise_suppression_very_high = 3
}

}
