//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 4.0.2
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace Unity.Services.Vivox {

internal enum vx_presence_state {
  presence_online = 0,
  presence_busy = 1,
  presence_brb = 2,
  presence_away = 3,
  presence_onthephone = 4,
  presence_offline = 5,
  presence_chat = 6,
  presence_extended_away = 7,
  presence_min = presence_online,
  presence_max = presence_extended_away
}

}
